version: "3.9"
services:
  db:
    image: keinos/sqlite3:latest
    volumes: 
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "7000:8080"
    depends_on:
      - db
