# Generated by Django 4.1.6 on 2023-02-17 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contactos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Descripcion')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Tlfno. móvil')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('unidades', models.CharField(default='', max_length=3, verbose_name='Unidades')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contactos.categorias')),
            ],
        ),
        migrations.AlterModelTable(
            name='contactos',
            table=None,
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='total')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='descuento')),
                ('totalventa', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='totalventa')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contactos.contactos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contactos.productos')),
            ],
        ),
    ]
